services:
  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      - POSTGRES_USER=chancellor
      - POSTGRES_DB=chancellor
      - POSTGRES_PASSWORD=chancellor
    ports:
      - 5432:5432
    volumes:
      - chancellor-db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U chancellor -d chancellor
      interval: 10s
      timeout: 3s
      retries: 3
  api:
    build:
      context: .
      target: dev
    container_name: api
    volumes:
      - ./src:/app/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://chancellor:chancellor@db:5432/chancellor
    ports:
      - 3000:3000

volumes:
  chancellor-db:
    name: chancellor-db
